function V = potential_from_multipoles(x,y,z,M,scale)
% return the potential at x,y,z, given a combination of input multipoles
V = M(1)+...
    scale*(-x*M(2)-y*M(3)-z*M(4))+...
    scale^2*((x^2-y^2)/2*M(5)+...
             (2*z^2-x^2-y^2)/2*M(6)+...
             (x*y)*M(7)+...
             (y*z)*M(8)+...
             (z*x)*M(9));
    